name: Lint Code Base

# Trigger the workflow on push and pull request events
on: [push, pull_request]

jobs:
  lint:
    # Specify that the job should run on the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run GitHub Super Linter
      - name: Run Super-Linter
        uses: github/super-linter@v4 
        env:
          # Required GitHub Token to allow Super Linter to add annotations to pull requests
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Set the main branch as the default branch
          DEFAULT_BRANCH: main

          # Enable linting for specific languages
          VALIDATE_BASH: true
          VALIDATE_YAML: true
          
          
          # Optional: Specify custom rules or configurations for linters
          LINTER_RULES_PATH: .github/linters # Custom rules folder if using one
